######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Food Justice Initiative"
theme = "wishfund-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

######################### Plugins #################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themify/css/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/dist/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick-carousel/slick/slick.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/dist/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick-carousel/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "High School Program"
  URL = "high-school"
  weight = 4

  ################# footer menu ##################

  [[menu.footer]]
  name = "about"
  URL = "about"
  weight = 2

[params]
logo = "images/fji-logo.png"
home = "Home"
# Contact Information
phone = "012548722120"
email = "foodjusticeinitiative@gmail.com"
location = "Flat 20, Reynolds Neck, North Helenaville, FV77"
copyright = "&copy; Food Justice Initiative 2022 (a theme by [themefisher](https://themefisher.com/))"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation top header
  [params.topHeader]
  enable = false

  # Navigation button
  [params.navBtn]
  enable = false
  label = "Get a quote"
  link = "donation"

  # Subscription
  [params.subscription]
  title = "Subscribe Us"
  content = "Subscribe to get latest news article and resources"


  #################### social icon ######################################
  #[[params.social]]
  #name = "Facebook"
  #icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  #link = "#"

  #[[params.social]]
  #name = "Twitter"
  #icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  #link = "#"

  #[[params.social]]
  #name = "Vimeo"
  #icon = "ti-vimeo-alt" # themify icon pack https://themify.me/themify-icons
  #link = "#"

  #[[params.social]]
  #name = "Github"
  #icon = "ti-github" # themify icon pack https://themify.me/themify-icons
  #link = "#"

############################# post share links ######################
#[[params.postShare]]
#icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
#name = "facebook"
#link = "#"

#[[params.postShare]]
#icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
#name = "twitter"
#link = "#"

#[[params.postShare]]
#icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
#name = "linkedin"
#link = "#"

#[[params.postShare]]
#icon = "ti-pinterest" # themify icon pack https://themify.me/themify-icons
#name = "pinterest"
#link = "#"
